name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      # Step 1: Set up Node.js (needed for npm)
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # NOTE: We have removed 'uses: iterative/setup-cml@v2'

      # Step 2: Install CML globally using npm
      - name: Install CML
        run: npm install -g @dvcorg/cml

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run main file to generate plot
        run: |
          python main.py
          
      - name: Run tests
        run: |
          python -m unittest discover

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # This step should now work correctly
          echo "# First Line of our Report" > report.md
          cml-publish test.png --md >> report.md
          cml-send-comment report.md